
language: python
cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - pip install flake8

before_script:
    - flake8 icepap --count --max-line-length=127 --statistics
script:
    - true

notifications:
    on_success: change

on_failure: change  # `always` will be the setting once code changes slow down